/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AVAILABLE_TRAINS.java
 *
 * Created on Oct 30, 2019, 7:02:59 PM
 */

/**
 *
 * @author JAYANTH,SANJAY
 */
import javax.swing.*;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
public class AVAILABLE_TRAINS extends javax.swing.JFrame {
        Connection con=null;
        Statement st=null;
        Statement st1=null;
        Statement st2=null;
        Statement st3=null;
        Statement st4=null;
        ResultSet rs=null;
        ResultSet rs1=null;

    /** Creates new form AVAILABLE_TRAINS */
    public AVAILABLE_TRAINS() {
        initComponents();
        jTextField1.setEditable(false);
        DefaultTableModel AVAILABLE_TRAINS=(DefaultTableModel)jTable1.getModel();
        try
        {
            con=DriverManager.getConnection("jdbc:mysql://localhost/RAILWAY","root","root");
            st=con.createStatement();
            String sql="SELECT * FROM SEARCH_TRAIN";
            rs=st.executeQuery(sql);
            try
            {
                st1=con.createStatement();
                String sql1="SELECT USERNAME FROM LOGIN";
                rs1=st1.executeQuery(sql1);
                while(rs1.next())
                {
                    String un=rs1.getString("USERNAME");
                    jTextField1.setText(un);
                }
                st1.close();
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,e.getMessage());
                System.exit(0);
            }
            while(rs.next())
            {
                String tn=rs.getString("TRAIN_NAME");
                String o=rs.getString("ORIGIN");
                String ds=rs.getString("DESTINATION");
                String at=rs.getString("ARRIVAL_TIME");
                String dt=rs.getString("DEPARTING_TIME");
                int f=Integer.parseInt(rs.getString("FARE"));
                String dd=rs.getString("DEPARTING_DATE");
                AVAILABLE_TRAINS.addRow(new Object[]{tn,o,ds,at,dt,f,dd});
            }
            st.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
            System.exit(0);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("AVAILABLE TRAINS");

        jPanel1.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TRAIN_NAME", "ORIGIN", "DESTINATION", "ARRIVAL_TIME", "DEPARTING_TIME", "FARE", "DERPARTING_DATE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setRowHeight(75);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(25, 96, 800, 340);

        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setText("BOOK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(837, 133, 70, 40);

        jButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton2.setText("BOOK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(837, 208, 70, 39);

        jButton3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton3.setText("BOOK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(837, 286, 70, 40);

        jButton4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton4.setText("BOOK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(837, 361, 67, 36);

        jTextField1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(611, 27, 104, 39);

        jButton5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton5.setText("BACK");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(617, 545, 110, 40);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("AVAILABLE TRAINS");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(350, 40, 129, 17);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ava_trains.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 950, 620);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 951, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        try
        {
            con=DriverManager.getConnection("jdbc:mysql://localhost/RAILWAY","root","root");
            st4=con.createStatement();
            String SQL2="DELETE FROM BOOKING";
            int x=st4.executeUpdate(SQL2);
            if(x>0)
            {
                AVAILABLE_TRAINS SEARCH_TRAIN_GUI=new AVAILABLE_TRAINS();
                new SEARCH_TRAIN_GUI().setVisible(true);
            }
            st4.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
            System.exit(0);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try
        {
            con=DriverManager.getConnection("jdbc:mysql://localhost/RAILWAY","root","root");
            st3=con.createStatement();
            String SQL="INSERT INTO BOOKING(TRAIN_NAME,ORIGIN,DESTINATION,ARRIVAL_TIME,DEPARTING_TIME,FARE,DEPARTING_DATE)(SELECT * FROM SEARCH_TRAIN LIMIT 1)";
            int a=st3.executeUpdate(SQL);
            if(a>0)
            {
                this.dispose();
                AVAILABLE_TRAINS contact_details=new AVAILABLE_TRAINS();
                new CONTACT_DETAILS().setVisible(true);
            }
            try
            {
                st2=con.createStatement();
                String sql="DELETE FROM SEARCH_TRAIN;";
                st2.executeUpdate(sql);
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,e.getMessage());
                System.exit(0);
            }
            st2.close();
            st3.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
            System.exit(0);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try
        {
            con=DriverManager.getConnection("jdbc:mysql://localhost/RAILWAY","root","root");
            st3=con.createStatement();
            String SQL="INSERT INTO BOOKING(TRAIN_NAME,ORIGIN,DESTINATION,ARRIVAL_TIME,DEPARTING_TIME,FARE,DEPARTING_DATE)(SELECT * FROM SEARCH_TRAIN LIMIT 1,1)";
            int a=st3.executeUpdate(SQL);
            if(a>0)
            {
                this.dispose();
                AVAILABLE_TRAINS contact_details=new AVAILABLE_TRAINS();
                new CONTACT_DETAILS().setVisible(true);
            }
            try
            {
                st2=con.createStatement();
                String sql="DELETE FROM SEARCH_TRAIN;";
                st2.executeUpdate(sql);
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,e.getMessage());
                System.exit(0);
            }
            st2.close();
            st3.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
            System.exit(0);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try
        {
            con=DriverManager.getConnection("jdbc:mysql://localhost/RAILWAY","root","root");
            st3=con.createStatement();
            String SQL="INSERT INTO BOOKING(TRAIN_NAME,ORIGIN,DESTINATION,ARRIVAL_TIME,DEPARTING_TIME,FARE,DEPARTING_DATE)(SELECT * FROM SEARCH_TRAIN LIMIT 2,1)";
            int a=st3.executeUpdate(SQL);
            if(a>0)
            {
                this.dispose();
                AVAILABLE_TRAINS contact_details=new AVAILABLE_TRAINS();
                new CONTACT_DETAILS().setVisible(true);
            }
            try
            {
                st2=con.createStatement();
                String sql="DELETE FROM SEARCH_TRAIN;";
                st2.executeUpdate(sql);
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,e.getMessage());
                System.exit(0);
            }
            st2.close();
            st3.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
            System.exit(0);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try
        {
            con=DriverManager.getConnection("jdbc:mysql://localhost/RAILWAY","root","root");
            st3=con.createStatement();
            String SQL="INSERT INTO BOOKING(TRAIN_NAME,ORIGIN,DESTINATION,ARRIVAL_TIME,DEPARTING_TIME,FARE,DEPARTING_DATE)(SELECT * FROM SEARCH_TRAIN LIMIT 3,1)";
            int a=st3.executeUpdate(SQL);
            if(a>0)
            {
                this.dispose();
                AVAILABLE_TRAINS contact_details=new AVAILABLE_TRAINS();
                new CONTACT_DETAILS().setVisible(true);
            }
            try
            {
                st2=con.createStatement();
                String sql="DELETE FROM SEARCH_TRAIN;";
                st2.executeUpdate(sql);
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,e.getMessage());
                System.exit(0);
            }
            st2.close();
            st3.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
            System.exit(0);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try
                {
                    Class.forName("java.sql.DriverManager");
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null,e.getMessage());
                }
                new AVAILABLE_TRAINS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
