/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CONTACT_DETAILS.java
 *
 * Created on Oct 30, 2019, 9:14:30 PM
 */

/**
 *
 * @author JAYANTH,SANJAY
 */
import java.sql.*;
import javax.swing.*;
public class CONTACT_DETAILS extends javax.swing.JFrame {
    Connection con=null;
    Statement st=null;
    Statement st1=null;
    ResultSet rs=null;
    /** Creates new form CONTACT_DETAILS */
    public CONTACT_DETAILS() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        jLabel11.setText("jLabel11");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("CONTACT DETAILS\n");
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel1.setText("CONTACT DETAILS");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(310, 30, 170, 22);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel2.setText("FIRST NAME");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(57, 97, 68, 15);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("LAST NAME");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(413, 97, 66, 15);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel4.setText("DATE OF BIRTH");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(57, 157, 85, 15);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel5.setText("ADDRESS");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(57, 239, 55, 15);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("CITY");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(413, 157, 25, 15);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel7.setText("COUNTRY");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(57, 362, 55, 15);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel8.setText("MOBILE NO.");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(57, 436, 67, 15);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel9.setText("EMAIL_ID");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(57, 513, 53, 15);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel10.setText("PINCODE");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(428, 362, 51, 15);

        jButton1.setFont(new java.awt.Font("Arial", 1, 14));
        jButton1.setText("SUBMIT & CONTINUE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(578, 430, 179, 27);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(182, 92, 133, 26);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(528, 91, 131, 29);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(182, 150, 133, 30);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(182, 224, 297, 96);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(528, 151, 131, 28);
        jPanel1.add(jTextField5);
        jTextField5.setBounds(182, 355, 125, 31);
        jPanel1.add(jTextField6);
        jTextField6.setBounds(182, 430, 157, 29);

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField7);
        jTextField7.setBounds(182, 506, 312, 31);
        jPanel1.add(jTextField8);
        jTextField8.setBounds(528, 344, 131, 30);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel12.setText("GENDER");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(609, 199, 46, 15);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Arial", 1, 12));
        jRadioButton1.setText("MALE");
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(602, 231, 57, 23);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Arial", 1, 12));
        jRadioButton2.setText("FEMALE");
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(697, 231, 71, 23);

        jButton2.setFont(new java.awt.Font("Arial", 1, 14));
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(578, 505, 137, 31);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/contact_details.png"))); // NOI18N
        jLabel13.setText("jLabel13");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(140, 0, 560, 600);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-3, -4, 830, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try
        {
            con=DriverManager.getConnection("jdbc:mysql://localhost/RAILWAY","root","root");
            st=con.createStatement();
            String fn=jTextField1.getText();
        String ln=jTextField2.getText();
        String dob=jTextField3.getText();
        String add=jTextArea1.getText();
        String g;
        if(jRadioButton1.isSelected())
        {
            g=jRadioButton1.getText();
        }
        else
        {
            g=jRadioButton2.getText();
        }
        String city=jTextField4.getText();
        String country=jTextField5.getText();
        String eid=jTextField7.getText();

        int pin=Integer.parseInt(jTextField8.getText());
            String sql="INSERT INTO CONTACT_DETAILS VALUES('"+fn+"','"+ln+"','"+dob+"','"+g+"','"+add+"','"+city+"','"+country+"',"+jTextField6.getText()+",'"+eid+"',"+pin+");";
            int n=st.executeUpdate(sql);
            if(n>0)
            {
                JOptionPane.showMessageDialog(null,"DETAILS SAVED");
                this.dispose();
                CONTACT_DETAILS PASSENGER_DETAILS=new CONTACT_DETAILS();
                new PASSENGER_DETAILS().setVisible(true);
            }
            else
            {
                JOptionPane.showMessageDialog(null,"NOT SAVED");
            }
            st.close();
            con.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
             System.exit(0);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try
        {
            con=DriverManager.getConnection("jdbc:mysql://localhost/RAILWAY","root","root");
            st1=con.createStatement();
            String SQL="DELETE FROM BOOKING";
            int x=st1.executeUpdate(SQL);
            if(x>0)
            {
                this.dispose();
                CONTACT_DETAILS AVAILABLE_TRAINS=new CONTACT_DETAILS();
                new AVAILABLE_TRAINS().setVisible(true);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
             System.exit(0);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try
                {
                    Class.forName("java.sql.DriverManager");
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null,e.getMessage());
                    System.exit(0);
                }
                new CONTACT_DETAILS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables

}
