/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DELETE_TRAIN.java
 *
 * Created on Oct 31, 2019, 12:45:58 AM
 */

/**
 *
 * @author JAYANTH,SANJAY
 */
import java.sql.*;
import javax.swing.*;
public class DELETE_TRAIN extends javax.swing.JFrame {
    Connection con=null;
    Statement st=null;
    ResultSet rs=null;

    /** Creates new form DELETE_TRAIN */
    public DELETE_TRAIN() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("DELETE TRAIN");

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DELETE TRAIN DETAILS");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(160, 52, 340, 29);
        jPanel1.add(jLabel2);
        jLabel2.setBounds(70, 110, 0, 0);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(290, 110, 147, 32);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DEPARTING DATE");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(90, 180, 160, 23);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(290, 170, 147, 31);

        jButton1.setFont(new java.awt.Font("Arial", 1, 18));
        jButton1.setText("DELETE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(122, 255, 140, 40);

        jButton2.setFont(new java.awt.Font("Arial", 1, 18));
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(460, 260, 150, 40);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TRAIN NAME");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(140, 120, 140, 22);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete_train.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 0, 740, 420);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try
        {
            con=DriverManager.getConnection("jdbc:mysql://localhost/RAILWAY","root","root");
            st=con.createStatement();
            String tn=jTextField1.getText();
            String dd=jTextField2.getText();
            String sql1="DELETE FROM TRAIN WHERE TRAIN_NAME='"+tn+"' AND DEPARTING_DATE='"+dd+"';";
            int x=st.executeUpdate(sql1);
            if(x>0)
            {
                JOptionPane.showMessageDialog(null,"DELETED");
            }
            st.close();
            con.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
            System.exit(0);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        ADD_TRAIN ADMIN=new ADD_TRAIN();
        new ADMIN().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try
                {
                    Class.forName("java.sql.DriverManager");
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null, e.getMessage());
                    System.exit(0);
                }
                new DELETE_TRAIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

}
