/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PASSENGER_DETAILS.java
 *
 * Created on Oct 30, 2019, 11:14:54 PM
 */

/**
 *
 * @author Admin
 */
import java.sql.*;
import javax.swing.*;
public class PASSENGER_DETAILS extends javax.swing.JFrame {
    Connection con=null;
    Statement st=null;

    /** Creates new form PASSENGER_DETAILS */
    public PASSENGER_DETAILS() {
        initComponents();
       
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        jLabel6.setText("PASSENGER 4");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("PASSENGER DETAILS");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(333, 44, 251, 28);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ENTER NO. OF PASSENGERS");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(178, 104, 159, 15);

        jComboBox1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(202, 145, 67, 21);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PAASENGER 1");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(110, 255, 80, 15);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PASSENGER 2");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(111, 340, 80, 15);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PASSENGER 3");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(111, 422, 80, 15);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("NAME");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(321, 195, 33, 15);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("AGE");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(490, 190, 42, 30);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("GENDER");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(637, 195, 46, 15);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(285, 246, 121, 33);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(448, 248, 150, 29);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(286, 334, 121, 27);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(449, 333, 150, 28);
        jPanel1.add(jTextField5);
        jTextField5.setBounds(286, 417, 121, 24);
        jPanel1.add(jTextField6);
        jTextField6.setBounds(449, 415, 150, 28);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jRadioButton1.setText("MALE");
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(641, 251, 61, 25);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jRadioButton2.setText("FEMALE");
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(716, 251, 73, 25);

        buttonGroup2.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jRadioButton3.setText("MALE");
        jPanel1.add(jRadioButton3);
        jRadioButton3.setBounds(642, 327, 61, 25);

        buttonGroup2.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jRadioButton4.setText("FEMALE");
        jPanel1.add(jRadioButton4);
        jRadioButton4.setBounds(717, 327, 73, 25);

        buttonGroup3.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jRadioButton5.setText("MALE");
        jPanel1.add(jRadioButton5);
        jRadioButton5.setBounds(642, 409, 61, 25);

        buttonGroup3.add(jRadioButton6);
        jRadioButton6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jRadioButton6.setText("FEMALE");
        jPanel1.add(jRadioButton6);
        jRadioButton6.setBounds(717, 409, 73, 25);

        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setText("SAVE & CONTINUE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(380, 470, 137, 23);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("ENTER THE TYPE OF COACH");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(593, 104, 156, 15);

        jComboBox2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AC First Class", "AC 2tier", "AC 3tier", "Sleeper" }));
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(611, 145, 115, 21);

        jButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(763, 40, 80, 30);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/update_image.jpg"))); // NOI18N
        jLabel12.setText("jLabel12");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(0, 0, 880, 510);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 881, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            con=DriverManager.getConnection("jdbc:mysql://localhost/RAILWAY","root","root");
            st=con.createStatement();
            if(jComboBox2.getSelectedIndex()==0)
            {
                if(jComboBox1.getSelectedIndex()==0 && jRadioButton1.isSelected())
                {
                    String a="INSERT INTO PASSENGER_DETAILS VALUES('"+jTextField1.getText()+"',"+jTextField2.getText()+",'"+jRadioButton1.getText()+"','"+jComboBox2.getSelectedItem()+"');";
                    int n=st.executeUpdate(a);
                    if(n>0)
                    {
                        JOptionPane.showMessageDialog(null,"DETAILS INSERTED");
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null,"DETAILS NOT INSERTED");
                    }
                    PASSENGER_DETAILS CONFIRM_BOOKING=new PASSENGER_DETAILS();
                    new CONFIRM_BOOKING().setVisible(true);
                }
                else if(jComboBox1.getSelectedIndex() == 0 && jRadioButton2.isSelected())
                {
                    String a="INSERT INTO PASSENGER_DETAILS VALUES('"+jTextField1.getText()+"',"+jTextField2.getText()+",'"+jRadioButton2.getText()+"','"+jComboBox2.getSelectedItem()+"');";
                    int n=st.executeUpdate(a);
                    if(n>0)
                    {
                        JOptionPane.showMessageDialog(null,"DETAILS INSERTED");
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null,"DETAILS NOT INSERTED");
                    }
                    PASSENGER_DETAILS CONFIRM_BOOKING=new PASSENGER_DETAILS();
                    new CONFIRM_BOOKING().setVisible(true);
                }


                else if(jComboBox1.getSelectedIndex() == 1 && jRadioButton1.isSelected())
                {
                    if(jRadioButton3.isSelected())
                    {
                    String a="INSERT INTO PASSENGER_DETAILS VALUES('"+jTextField1.getText()+"',"+jTextField2.getText()+",'"+jRadioButton1.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField3.getText()+"',"+jTextField4.getText()+",'"+jRadioButton3.getText()+"','"+jComboBox2.getSelectedItem()+"');";
                    int n=st.executeUpdate(a);
                    if(n>0)
                    {
                        JOptionPane.showMessageDialog(null,"DETAILS INSERTED");
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null,"DETAILS NOT INSERTED");
                    }
                    PASSENGER_DETAILS CONFIRM_BOOKING=new PASSENGER_DETAILS();
                    new CONFIRM_BOOKING().setVisible(true);
                    }
                    else if(jRadioButton4.isSelected())
                    {
                        String a="INSERT INTO PASSENGER_DETAILS VALUES('"+jTextField1.getText()+"',"+jTextField2.getText()+",'"+jRadioButton1.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField3.getText()+"',"+jTextField4.getText()+",'"+jRadioButton4.getText()+"','"+jComboBox2.getSelectedItem()+"');";
                        int n=st.executeUpdate(a);
                        if(n>0)
                        {
                            JOptionPane.showMessageDialog(null,"DETAILS INSERTED");
                        }
                        else
                        {
                         JOptionPane.showMessageDialog(null,"DETAILS NOT INSERTED");
                        }
                    PASSENGER_DETAILS CONFIRM_BOOKING=new PASSENGER_DETAILS();
                    new CONFIRM_BOOKING().setVisible(true);
                    }
                }
                else if(jComboBox1.getSelectedIndex() == 1 && jRadioButton2.isSelected())
                {
                    if(jRadioButton3.isSelected())
                    {
                    String a="INSERT INTO PASSENGER_DETAILS VALUES('"+jTextField1.getText()+"',"+jTextField2.getText()+",'"+jRadioButton2.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField3.getText()+"',"+jTextField4.getText()+",'"+jRadioButton3.getText()+"','"+jComboBox2.getSelectedItem()+"');";
                    int n=st.executeUpdate(a);
                    if(n>0)
                    {
                        JOptionPane.showMessageDialog(null,"DETAILS INSERTED");
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null,"DETAILS NOT INSERTED");
                    }
                    PASSENGER_DETAILS CONFIRM_BOOKING=new PASSENGER_DETAILS();
                    new CONFIRM_BOOKING().setVisible(true);
                    }
                    else if(jRadioButton4.isSelected())
                    {
                        String a="INSERT INTO PASSENGER_DETAILS VALUES('"+jTextField1.getText()+"',"+jTextField2.getText()+",'"+jRadioButton2.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField3.getText()+"',"+jTextField4.getText()+",'"+jRadioButton4.getText()+"','"+jComboBox2.getSelectedItem()+"');";
                        int n=st.executeUpdate(a);
                        if(n>0)
                        {
                            JOptionPane.showMessageDialog(null,"DETAILS INSERTED");
                        }
                        else
                        {
                         JOptionPane.showMessageDialog(null,"DETAILS NOT INSERTED");
                        }
                    PASSENGER_DETAILS CONFIRM_BOOKING=new PASSENGER_DETAILS();
                    new CONFIRM_BOOKING().setVisible(true);
                    }
                }


                else if(jComboBox1.getSelectedIndex()==2 && jRadioButton1.isSelected())
                {
                    if(jRadioButton3.isSelected())
                    {
                        if(jRadioButton5.isSelected())
                        {
                            String a="INSERT INTO PASSENGER_DETAILS VALUES('"+jTextField1.getText()+"',"+jTextField2.getText()+",'"+jRadioButton1.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField3.getText()+"',"+jTextField4.getText()+",'"+jRadioButton3.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField5.getText()+"',"+jTextField6.getText()+",'"+jRadioButton5.getText()+"','"+jComboBox2.getSelectedItem()+"');";
                            int n=st.executeUpdate(a);
                            if(n>0)
                            {
                                JOptionPane.showMessageDialog(null,"DETAILS INSERTED");
                            }
                            else
                            {
                                JOptionPane.showMessageDialog(null,"DETAILS NOT INSERTED");
                            }
                            PASSENGER_DETAILS CONFIRM_BOOKING=new PASSENGER_DETAILS();
                            new CONFIRM_BOOKING().setVisible(true);
                        }
                        else if(jRadioButton6.isSelected())
                        {
                            String a="INSERT INTO PASSENGER_DETAILS VALUES('"+jTextField1.getText()+"',"+jTextField2.getText()+",'"+jRadioButton1.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField3.getText()+"',"+jTextField4.getText()+",'"+jRadioButton3.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField5.getText()+"',"+jTextField6.getText()+",'"+jRadioButton6.getText()+"','"+jComboBox2.getSelectedItem()+"');";
                            int n=st.executeUpdate(a);
                            if(n>0)
                            {
                                JOptionPane.showMessageDialog(null,"DETAILS INSERTED");
                            }
                            else
                            {
                                JOptionPane.showMessageDialog(null,"DETAILS NOT INSERTED");
                            }
                            PASSENGER_DETAILS CONFIRM_BOOKING=new PASSENGER_DETAILS();
                            new CONFIRM_BOOKING().setVisible(true);
                        }
                    }
                    else if(jRadioButton4.isSelected())
                    {
                        if(jRadioButton5.isSelected())
                        {
                            String a="INSERT INTO PASSENGER_DETAILS VALUES('"+jTextField1.getText()+"',"+jTextField2.getText()+",'"+jRadioButton1.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField3.getText()+"',"+jTextField4.getText()+",'"+jRadioButton4.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField5.getText()+"',"+jTextField6.getText()+",'"+jRadioButton5.getText()+"','"+jComboBox2.getSelectedItem()+"');";
                            int n=st.executeUpdate(a);
                            if(n>0)
                            {
                                JOptionPane.showMessageDialog(null,"DETAILS INSERTED");
                            }
                            else
                            {
                                JOptionPane.showMessageDialog(null,"DETAILS NOT INSERTED");
                            }
                            PASSENGER_DETAILS CONFIRM_BOOKING=new PASSENGER_DETAILS();
                            new CONFIRM_BOOKING().setVisible(true);
                        }
                        else if(jRadioButton6.isSelected())
                        {
                            String a="INSERT INTO PASSENGER_DETAILS VALUES('"+jTextField1.getText()+"',"+jTextField2.getText()+",'"+jRadioButton1.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField3.getText()+"',"+jTextField4.getText()+",'"+jRadioButton4.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField5.getText()+"',"+jTextField6.getText()+",'"+jRadioButton6.getText()+"','"+jComboBox2.getSelectedItem()+"');";
                            int n=st.executeUpdate(a);
                            if(n>0)
                            {
                                JOptionPane.showMessageDialog(null,"DETAILS INSERTED");
                            }
                            else
                            {
                                JOptionPane.showMessageDialog(null,"DETAILS NOT INSERTED");
                            }
                            PASSENGER_DETAILS CONFIRM_BOOKING=new PASSENGER_DETAILS();
                            new CONFIRM_BOOKING().setVisible(true);
                        }
                    }
                }
                else if(jComboBox1.getSelectedIndex()==2 && jRadioButton2.isSelected())
                {
                    if(jRadioButton3.isSelected())
                    {
                        if(jRadioButton5.isSelected())
                        {
                            String a="INSERT INTO PASSENGER_DETAILS VALUES('"+jTextField1.getText()+"',"+jTextField2.getText()+",'"+jRadioButton2.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField3.getText()+"',"+jTextField4.getText()+",'"+jRadioButton3.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField5.getText()+"',"+jTextField6.getText()+",'"+jRadioButton5.getText()+"','"+jComboBox2.getSelectedItem()+"');";
                            int n=st.executeUpdate(a);
                            if(n>0)
                            {
                                JOptionPane.showMessageDialog(null,"DETAILS INSERTED");
                            }
                            else
                            {
                                JOptionPane.showMessageDialog(null,"DETAILS NOT INSERTED");
                            }
                            PASSENGER_DETAILS CONFIRM_BOOKING=new PASSENGER_DETAILS();
                            new CONFIRM_BOOKING().setVisible(true);
                        }
                        else if(jRadioButton6.isSelected())
                        {
                            String a="INSERT INTO PASSENGER_DETAILS VALUES('"+jTextField1.getText()+"',"+jTextField2.getText()+",'"+jRadioButton2.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField3.getText()+"',"+jTextField4.getText()+",'"+jRadioButton3.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField5.getText()+"',"+jTextField6.getText()+",'"+jRadioButton6.getText()+"','"+jComboBox2.getSelectedItem()+"');";
                            int n=st.executeUpdate(a);
                            if(n>0)
                            {
                                JOptionPane.showMessageDialog(null,"DETAILS INSERTED");
                            }
                            else
                            {
                                JOptionPane.showMessageDialog(null,"DETAILS NOT INSERTED");
                            }
                            PASSENGER_DETAILS CONFIRM_BOOKING=new PASSENGER_DETAILS();
                            new CONFIRM_BOOKING().setVisible(true);
                        }
                      }
                      else if(jRadioButton4.isSelected())
                      {
                        if(jRadioButton5.isSelected())
                        {
                            String a="INSERT INTO PASSENGER_DETAILS VALUES('"+jTextField1.getText()+"',"+jTextField2.getText()+",'"+jRadioButton2.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField3.getText()+"',"+jTextField4.getText()+",'"+jRadioButton4.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField5.getText()+"',"+jTextField6.getText()+",'"+jRadioButton5.getText()+"','"+jComboBox2.getSelectedItem()+"');";
                            int n=st.executeUpdate(a);
                            if(n>0)
                            {
                                JOptionPane.showMessageDialog(null,"DETAILS INSERTED");
                            }
                            else
                            {
                                JOptionPane.showMessageDialog(null,"DETAILS NOT INSERTED");
                            }
                            PASSENGER_DETAILS CONFIRM_BOOKING=new PASSENGER_DETAILS();
                            new CONFIRM_BOOKING().setVisible(true);
                         }
                         else if(jRadioButton6.isSelected())
                         {
                            String a="INSERT INTO PASSENGER_DETAILS VALUES('"+jTextField1.getText()+"',"+jTextField2.getText()+",'"+jRadioButton2.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField3.getText()+"',"+jTextField4.getText()+",'"+jRadioButton4.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField5.getText()+"',"+jTextField6.getText()+",'"+jRadioButton6.getText()+"','"+jComboBox2.getSelectedItem()+"');";
                            int n=st.executeUpdate(a);
                            if(n>0)
                            {
                                JOptionPane.showMessageDialog(null,"DETAILS INSERTED");
                            }
                            else
                            {
                                JOptionPane.showMessageDialog(null,"DETAILS NOT INSERTED");
                            }
                            PASSENGER_DETAILS CONFIRM_BOOKING=new PASSENGER_DETAILS();
                            new CONFIRM_BOOKING().setVisible(true);
                         }
                      }
                 }
            }



            else if(jComboBox2.getSelectedIndex() == 1)
            {
                if(jComboBox1.getSelectedIndex()==0 && jRadioButton1.isSelected())
                {
                    String a="INSERT INTO PASSENGER_DETAILS VALUES('"+jTextField1.getText()+"',"+jTextField2.getText()+",'"+jRadioButton1.getText()+"','"+jComboBox2.getSelectedItem()+"');";
                    int n=st.executeUpdate(a);
                    if(n>0)
                    {
                        JOptionPane.showMessageDialog(null,"DETAILS INSERTED");
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null,"DETAILS NOT INSERTED");
                    }
                    PASSENGER_DETAILS CONFIRM_BOOKING=new PASSENGER_DETAILS();
                    new CONFIRM_BOOKING().setVisible(true);
                }
                else if(jComboBox1.getSelectedIndex() == 0 && jRadioButton2.isSelected())
                {
                    String a="INSERT INTO PASSENGER_DETAILS VALUES('"+jTextField1.getText()+"',"+jTextField2.getText()+",'"+jRadioButton2.getText()+"','"+jComboBox2.getSelectedItem()+"');";
                    int n=st.executeUpdate(a);
                    if(n>0)
                    {
                        JOptionPane.showMessageDialog(null,"DETAILS INSERTED");
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null,"DETAILS NOT INSERTED");
                    }
                    PASSENGER_DETAILS CONFIRM_BOOKING=new PASSENGER_DETAILS();
                    new CONFIRM_BOOKING().setVisible(true);
                }


                else if(jComboBox1.getSelectedIndex() == 1 && jRadioButton1.isSelected())
                {
                    if(jRadioButton3.isSelected())
                    {
                    String a="INSERT INTO PASSENGER_DETAILS VALUES('"+jTextField1.getText()+"',"+jTextField2.getText()+",'"+jRadioButton1.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField3.getText()+"',"+jTextField4.getText()+",'"+jRadioButton3.getText()+"','"+jComboBox2.getSelectedItem()+"');";
                    int n=st.executeUpdate(a);
                    if(n>0)
                    {
                        JOptionPane.showMessageDialog(null,"DETAILS INSERTED");
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null,"DETAILS NOT INSERTED");
                    }
                    PASSENGER_DETAILS CONFIRM_BOOKING=new PASSENGER_DETAILS();
                    new CONFIRM_BOOKING().setVisible(true);
                    }
                    else if(jRadioButton4.isSelected())
                    {
                        String a="INSERT INTO PASSENGER_DETAILS VALUES('"+jTextField1.getText()+"',"+jTextField2.getText()+",'"+jRadioButton1.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField3.getText()+"',"+jTextField4.getText()+",'"+jRadioButton4.getText()+"','"+jComboBox2.getSelectedItem()+"');";
                        int n=st.executeUpdate(a);
                        if(n>0)
                        {
                            JOptionPane.showMessageDialog(null,"DETAILS INSERTED");
                        }
                        else
                        {
                         JOptionPane.showMessageDialog(null,"DETAILS NOT INSERTED");
                        }
                    PASSENGER_DETAILS CONFIRM_BOOKING=new PASSENGER_DETAILS();
                    new CONFIRM_BOOKING().setVisible(true);
                    }
                }
                else if(jComboBox1.getSelectedIndex() == 1 && jRadioButton2.isSelected())
                {
                    if(jRadioButton3.isSelected())
                    {
                    String a="INSERT INTO PASSENGER_DETAILS VALUES('"+jTextField1.getText()+"',"+jTextField2.getText()+",'"+jRadioButton2.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField3.getText()+"',"+jTextField4.getText()+",'"+jRadioButton3.getText()+"','"+jComboBox2.getSelectedItem()+"');";
                    int n=st.executeUpdate(a);
                    if(n>0)
                    {
                        JOptionPane.showMessageDialog(null,"DETAILS INSERTED");
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null,"DETAILS NOT INSERTED");
                    }
                    PASSENGER_DETAILS CONFIRM_BOOKING=new PASSENGER_DETAILS();
                    new CONFIRM_BOOKING().setVisible(true);
                    }
                    else if(jRadioButton4.isSelected())
                    {
                        String a="INSERT INTO PASSENGER_DETAILS VALUES('"+jTextField1.getText()+"',"+jTextField2.getText()+",'"+jRadioButton2.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField3.getText()+"',"+jTextField4.getText()+",'"+jRadioButton4.getText()+"','"+jComboBox2.getSelectedItem()+"');";
                        int n=st.executeUpdate(a);
                        if(n>0)
                        {
                            JOptionPane.showMessageDialog(null,"DETAILS INSERTED");
                        }
                        else
                        {
                         JOptionPane.showMessageDialog(null,"DETAILS NOT INSERTED");
                        }
                    PASSENGER_DETAILS CONFIRM_BOOKING=new PASSENGER_DETAILS();
                    new CONFIRM_BOOKING().setVisible(true);
                    }
                }


                else if(jComboBox1.getSelectedIndex()==2 && jRadioButton1.isSelected())
                {
                    if(jRadioButton3.isSelected())
                    {
                        if(jRadioButton5.isSelected())
                        {
                            String a="INSERT INTO PASSENGER_DETAILS VALUES('"+jTextField1.getText()+"',"+jTextField2.getText()+",'"+jRadioButton1.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField3.getText()+"',"+jTextField4.getText()+",'"+jRadioButton3.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField5.getText()+"',"+jTextField6.getText()+",'"+jRadioButton5.getText()+"','"+jComboBox2.getSelectedItem()+"');";
                            int n=st.executeUpdate(a);
                            if(n>0)
                            {
                                JOptionPane.showMessageDialog(null,"DETAILS INSERTED");
                            }
                            else
                            {
                                JOptionPane.showMessageDialog(null,"DETAILS NOT INSERTED");
                            }
                            PASSENGER_DETAILS CONFIRM_BOOKING=new PASSENGER_DETAILS();
                            new CONFIRM_BOOKING().setVisible(true);
                        }
                        else if(jRadioButton6.isSelected())
                        {
                            String a="INSERT INTO PASSENGER_DETAILS VALUES('"+jTextField1.getText()+"',"+jTextField2.getText()+",'"+jRadioButton1.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField3.getText()+"',"+jTextField4.getText()+",'"+jRadioButton3.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField5.getText()+"',"+jTextField6.getText()+",'"+jRadioButton6.getText()+"','"+jComboBox2.getSelectedItem()+"');";
                            int n=st.executeUpdate(a);
                            if(n>0)
                            {
                                JOptionPane.showMessageDialog(null,"DETAILS INSERTED");
                            }
                            else
                            {
                                JOptionPane.showMessageDialog(null,"DETAILS NOT INSERTED");
                            }
                            PASSENGER_DETAILS CONFIRM_BOOKING=new PASSENGER_DETAILS();
                            new CONFIRM_BOOKING().setVisible(true);
                        }
                    }
                    else if(jRadioButton4.isSelected())
                    {
                        if(jRadioButton5.isSelected())
                        {
                            String a="INSERT INTO PASSENGER_DETAILS VALUES('"+jTextField1.getText()+"',"+jTextField2.getText()+",'"+jRadioButton1.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField3.getText()+"',"+jTextField4.getText()+",'"+jRadioButton4.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField5.getText()+"',"+jTextField6.getText()+",'"+jRadioButton5.getText()+"','"+jComboBox2.getSelectedItem()+"');";
                            int n=st.executeUpdate(a);
                            if(n>0)
                            {
                                JOptionPane.showMessageDialog(null,"DETAILS INSERTED");
                            }
                            else
                            {
                                JOptionPane.showMessageDialog(null,"DETAILS NOT INSERTED");
                            }
                            PASSENGER_DETAILS CONFIRM_BOOKING=new PASSENGER_DETAILS();
                            new CONFIRM_BOOKING().setVisible(true);
                        }
                        else if(jRadioButton6.isSelected())
                        {
                            String a="INSERT INTO PASSENGER_DETAILS VALUES('"+jTextField1.getText()+"',"+jTextField2.getText()+",'"+jRadioButton1.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField3.getText()+"',"+jTextField4.getText()+",'"+jRadioButton4.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField5.getText()+"',"+jTextField6.getText()+",'"+jRadioButton6.getText()+"','"+jComboBox2.getSelectedItem()+"');";
                            int n=st.executeUpdate(a);
                            if(n>0)
                            {
                                JOptionPane.showMessageDialog(null,"DETAILS INSERTED");
                            }
                            else
                            {
                                JOptionPane.showMessageDialog(null,"DETAILS NOT INSERTED");
                            }
                            PASSENGER_DETAILS CONFIRM_BOOKING=new PASSENGER_DETAILS();
                            new CONFIRM_BOOKING().setVisible(true);
                        }
                    }
                }
                else if(jComboBox1.getSelectedIndex()==2 && jRadioButton2.isSelected())
                {
                    if(jRadioButton3.isSelected())
                    {
                        if(jRadioButton5.isSelected())
                        {
                            String a="INSERT INTO PASSENGER_DETAILS VALUES('"+jTextField1.getText()+"',"+jTextField2.getText()+",'"+jRadioButton2.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField3.getText()+"',"+jTextField4.getText()+",'"+jRadioButton3.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField5.getText()+"',"+jTextField6.getText()+",'"+jRadioButton5.getText()+"','"+jComboBox2.getSelectedItem()+"');";
                            int n=st.executeUpdate(a);
                            if(n>0)
                            {
                                JOptionPane.showMessageDialog(null,"DETAILS INSERTED");
                            }
                            else
                            {
                                JOptionPane.showMessageDialog(null,"DETAILS NOT INSERTED");
                            }
                            PASSENGER_DETAILS CONFIRM_BOOKING=new PASSENGER_DETAILS();
                            new CONFIRM_BOOKING().setVisible(true);
                        }
                        else if(jRadioButton6.isSelected())
                        {
                            String a="INSERT INTO PASSENGER_DETAILS VALUES('"+jTextField1.getText()+"',"+jTextField2.getText()+",'"+jRadioButton2.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField3.getText()+"',"+jTextField4.getText()+",'"+jRadioButton3.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField5.getText()+"',"+jTextField6.getText()+",'"+jRadioButton6.getText()+"','"+jComboBox2.getSelectedItem()+"');";
                            int n=st.executeUpdate(a);
                            if(n>0)
                            {
                                JOptionPane.showMessageDialog(null,"DETAILS INSERTED");
                            }
                            else
                            {
                                JOptionPane.showMessageDialog(null,"DETAILS NOT INSERTED");
                            }
                            PASSENGER_DETAILS CONFIRM_BOOKING=new PASSENGER_DETAILS();
                            new CONFIRM_BOOKING().setVisible(true);
                        }
                      }
                      else if(jRadioButton4.isSelected())
                      {
                        if(jRadioButton5.isSelected())
                        {
                            String a="INSERT INTO PASSENGER_DETAILS VALUES('"+jTextField1.getText()+"',"+jTextField2.getText()+",'"+jRadioButton2.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField3.getText()+"',"+jTextField4.getText()+",'"+jRadioButton4.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField5.getText()+"',"+jTextField6.getText()+",'"+jRadioButton5.getText()+"','"+jComboBox2.getSelectedItem()+"');";
                            int n=st.executeUpdate(a);
                            if(n>0)
                            {
                                JOptionPane.showMessageDialog(null,"DETAILS INSERTED");
                            }
                            else
                            {
                                JOptionPane.showMessageDialog(null,"DETAILS NOT INSERTED");
                            }
                            PASSENGER_DETAILS CONFIRM_BOOKING=new PASSENGER_DETAILS();
                            new CONFIRM_BOOKING().setVisible(true);
                         }
                         else if(jRadioButton6.isSelected())
                         {
                            String a="INSERT INTO PASSENGER_DETAILS VALUES('"+jTextField1.getText()+"',"+jTextField2.getText()+",'"+jRadioButton2.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField3.getText()+"',"+jTextField4.getText()+",'"+jRadioButton4.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField5.getText()+"',"+jTextField6.getText()+",'"+jRadioButton6.getText()+"','"+jComboBox2.getSelectedItem()+"');";
                            int n=st.executeUpdate(a);
                            if(n>0)
                            {
                                JOptionPane.showMessageDialog(null,"DETAILS INSERTED");
                            }
                            else
                            {
                                JOptionPane.showMessageDialog(null,"DETAILS NOT INSERTED");
                            }
                            PASSENGER_DETAILS CONFIRM_BOOKING=new PASSENGER_DETAILS();
                            new CONFIRM_BOOKING().setVisible(true);
                         }
                      }
                 }
            }






            else if(jComboBox2.getSelectedIndex() == 2)
            {
                if(jComboBox1.getSelectedIndex()==0 && jRadioButton1.isSelected())
                {
                    String a="INSERT INTO PASSENGER_DETAILS VALUES('"+jTextField1.getText()+"',"+jTextField2.getText()+",'"+jRadioButton1.getText()+"','"+jComboBox2.getSelectedItem()+"');";
                    int n=st.executeUpdate(a);
                    if(n>0)
                    {
                        JOptionPane.showMessageDialog(null,"DETAILS INSERTED");
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null,"DETAILS NOT INSERTED");
                    }
                    PASSENGER_DETAILS CONFIRM_BOOKING=new PASSENGER_DETAILS();
                    new CONFIRM_BOOKING().setVisible(true);
                }
                else if(jComboBox1.getSelectedIndex() == 0 && jRadioButton2.isSelected())
                {
                    String a="INSERT INTO PASSENGER_DETAILS VALUES('"+jTextField1.getText()+"',"+jTextField2.getText()+",'"+jRadioButton2.getText()+"','"+jComboBox2.getSelectedItem()+"');";
                    int n=st.executeUpdate(a);
                    if(n>0)
                    {
                        JOptionPane.showMessageDialog(null,"DETAILS INSERTED");
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null,"DETAILS NOT INSERTED");
                    }
                    PASSENGER_DETAILS CONFIRM_BOOKING=new PASSENGER_DETAILS();
                    new CONFIRM_BOOKING().setVisible(true);
                }


                else if(jComboBox1.getSelectedIndex() == 1 && jRadioButton1.isSelected())
                {
                    if(jRadioButton3.isSelected())
                    {
                    String a="INSERT INTO PASSENGER_DETAILS VALUES('"+jTextField1.getText()+"',"+jTextField2.getText()+",'"+jRadioButton1.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField3.getText()+"',"+jTextField4.getText()+",'"+jRadioButton3.getText()+"','"+jComboBox2.getSelectedItem()+"');";
                    int n=st.executeUpdate(a);
                    if(n>0)
                    {
                        JOptionPane.showMessageDialog(null,"DETAILS INSERTED");
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null,"DETAILS NOT INSERTED");
                    }
                    PASSENGER_DETAILS CONFIRM_BOOKING=new PASSENGER_DETAILS();
                    new CONFIRM_BOOKING().setVisible(true);
                    }
                    else if(jRadioButton4.isSelected())
                    {
                        String a="INSERT INTO PASSENGER_DETAILS VALUES('"+jTextField1.getText()+"',"+jTextField2.getText()+",'"+jRadioButton1.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField3.getText()+"',"+jTextField4.getText()+",'"+jRadioButton4.getText()+"','"+jComboBox2.getSelectedItem()+"');";
                        int n=st.executeUpdate(a);
                        if(n>0)
                        {
                            JOptionPane.showMessageDialog(null,"DETAILS INSERTED");
                        }
                        else
                        {
                         JOptionPane.showMessageDialog(null,"DETAILS NOT INSERTED");
                        }
                    PASSENGER_DETAILS CONFIRM_BOOKING=new PASSENGER_DETAILS();
                    new CONFIRM_BOOKING().setVisible(true);
                    }
                }
                else if(jComboBox1.getSelectedIndex() == 1 && jRadioButton2.isSelected())
                {
                    if(jRadioButton3.isSelected())
                    {
                    String a="INSERT INTO PASSENGER_DETAILS VALUES('"+jTextField1.getText()+"',"+jTextField2.getText()+",'"+jRadioButton2.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField3.getText()+"',"+jTextField4.getText()+",'"+jRadioButton3.getText()+"','"+jComboBox2.getSelectedItem()+"');";
                    int n=st.executeUpdate(a);
                    if(n>0)
                    {
                        JOptionPane.showMessageDialog(null,"DETAILS INSERTED");
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null,"DETAILS NOT INSERTED");
                    }
                    PASSENGER_DETAILS CONFIRM_BOOKING=new PASSENGER_DETAILS();
                    new CONFIRM_BOOKING().setVisible(true);
                    }
                    else if(jRadioButton4.isSelected())
                    {
                        String a="INSERT INTO PASSENGER_DETAILS VALUES('"+jTextField1.getText()+"',"+jTextField2.getText()+",'"+jRadioButton2.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField3.getText()+"',"+jTextField4.getText()+",'"+jRadioButton4.getText()+"','"+jComboBox2.getSelectedItem()+"');";
                        int n=st.executeUpdate(a);
                        if(n>0)
                        {
                            JOptionPane.showMessageDialog(null,"DETAILS INSERTED");
                        }
                        else
                        {
                         JOptionPane.showMessageDialog(null,"DETAILS NOT INSERTED");
                        }
                    PASSENGER_DETAILS CONFIRM_BOOKING=new PASSENGER_DETAILS();
                    new CONFIRM_BOOKING().setVisible(true);
                    }
                }


                else if(jComboBox1.getSelectedIndex()==2 && jRadioButton1.isSelected())
                {
                    if(jRadioButton3.isSelected())
                    {
                        if(jRadioButton5.isSelected())
                        {
                            String a="INSERT INTO PASSENGER_DETAILS VALUES('"+jTextField1.getText()+"',"+jTextField2.getText()+",'"+jRadioButton1.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField3.getText()+"',"+jTextField4.getText()+",'"+jRadioButton3.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField5.getText()+"',"+jTextField6.getText()+",'"+jRadioButton5.getText()+"','"+jComboBox2.getSelectedItem()+"');";
                            int n=st.executeUpdate(a);
                            if(n>0)
                            {
                                JOptionPane.showMessageDialog(null,"DETAILS INSERTED");
                            }
                            else
                            {
                                JOptionPane.showMessageDialog(null,"DETAILS NOT INSERTED");
                            }
                            PASSENGER_DETAILS CONFIRM_BOOKING=new PASSENGER_DETAILS();
                            new CONFIRM_BOOKING().setVisible(true);
                        }
                        else if(jRadioButton6.isSelected())
                        {
                            String a="INSERT INTO PASSENGER_DETAILS VALUES('"+jTextField1.getText()+"',"+jTextField2.getText()+",'"+jRadioButton1.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField3.getText()+"',"+jTextField4.getText()+",'"+jRadioButton3.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField5.getText()+"',"+jTextField6.getText()+",'"+jRadioButton6.getText()+"','"+jComboBox2.getSelectedItem()+"');";
                            int n=st.executeUpdate(a);
                            if(n>0)
                            {
                                JOptionPane.showMessageDialog(null,"DETAILS INSERTED");
                            }
                            else
                            {
                                JOptionPane.showMessageDialog(null,"DETAILS NOT INSERTED");
                            }
                            PASSENGER_DETAILS CONFIRM_BOOKING=new PASSENGER_DETAILS();
                            new CONFIRM_BOOKING().setVisible(true);
                        }
                    }
                    else if(jRadioButton4.isSelected())
                    {
                        if(jRadioButton5.isSelected())
                        {
                            String a="INSERT INTO PASSENGER_DETAILS VALUES('"+jTextField1.getText()+"',"+jTextField2.getText()+",'"+jRadioButton1.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField3.getText()+"',"+jTextField4.getText()+",'"+jRadioButton4.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField5.getText()+"',"+jTextField6.getText()+",'"+jRadioButton5.getText()+"','"+jComboBox2.getSelectedItem()+"');";
                            int n=st.executeUpdate(a);
                            if(n>0)
                            {
                                JOptionPane.showMessageDialog(null,"DETAILS INSERTED");
                            }
                            else
                            {
                                JOptionPane.showMessageDialog(null,"DETAILS NOT INSERTED");
                            }
                            PASSENGER_DETAILS CONFIRM_BOOKING=new PASSENGER_DETAILS();
                            new CONFIRM_BOOKING().setVisible(true);
                        }
                        else if(jRadioButton6.isSelected())
                        {
                            String a="INSERT INTO PASSENGER_DETAILS VALUES('"+jTextField1.getText()+"',"+jTextField2.getText()+",'"+jRadioButton1.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField3.getText()+"',"+jTextField4.getText()+",'"+jRadioButton4.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField5.getText()+"',"+jTextField6.getText()+",'"+jRadioButton6.getText()+"','"+jComboBox2.getSelectedItem()+"');";
                            int n=st.executeUpdate(a);
                            if(n>0)
                            {
                                JOptionPane.showMessageDialog(null,"DETAILS INSERTED");
                            }
                            else
                            {
                                JOptionPane.showMessageDialog(null,"DETAILS NOT INSERTED");
                            }
                            PASSENGER_DETAILS CONFIRM_BOOKING=new PASSENGER_DETAILS();
                            new CONFIRM_BOOKING().setVisible(true);
                        }
                    }
                }
                else if(jComboBox1.getSelectedIndex()==2 && jRadioButton2.isSelected())
                {
                    if(jRadioButton3.isSelected())
                    {
                        if(jRadioButton5.isSelected())
                        {
                            String a="INSERT INTO PASSENGER_DETAILS VALUES('"+jTextField1.getText()+"',"+jTextField2.getText()+",'"+jRadioButton2.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField3.getText()+"',"+jTextField4.getText()+",'"+jRadioButton3.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField5.getText()+"',"+jTextField6.getText()+",'"+jRadioButton5.getText()+"','"+jComboBox2.getSelectedItem()+"');";
                            int n=st.executeUpdate(a);
                            if(n>0)
                            {
                                JOptionPane.showMessageDialog(null,"DETAILS INSERTED");
                            }
                            else
                            {
                                JOptionPane.showMessageDialog(null,"DETAILS NOT INSERTED");
                            }
                            PASSENGER_DETAILS CONFIRM_BOOKING=new PASSENGER_DETAILS();
                            new CONFIRM_BOOKING().setVisible(true);
                        }
                        else if(jRadioButton6.isSelected())
                        {
                            String a="INSERT INTO PASSENGER_DETAILS VALUES('"+jTextField1.getText()+"',"+jTextField2.getText()+",'"+jRadioButton2.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField3.getText()+"',"+jTextField4.getText()+",'"+jRadioButton3.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField5.getText()+"',"+jTextField6.getText()+",'"+jRadioButton6.getText()+"','"+jComboBox2.getSelectedItem()+"');";
                            int n=st.executeUpdate(a);
                            if(n>0)
                            {
                                JOptionPane.showMessageDialog(null,"DETAILS INSERTED");
                            }
                            else
                            {
                                JOptionPane.showMessageDialog(null,"DETAILS NOT INSERTED");
                            }
                            PASSENGER_DETAILS CONFIRM_BOOKING=new PASSENGER_DETAILS();
                            new CONFIRM_BOOKING().setVisible(true);
                        }
                      }
                      else if(jRadioButton4.isSelected())
                      {
                        if(jRadioButton5.isSelected())
                        {
                            String a="INSERT INTO PASSENGER_DETAILS VALUES('"+jTextField1.getText()+"',"+jTextField2.getText()+",'"+jRadioButton2.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField3.getText()+"',"+jTextField4.getText()+",'"+jRadioButton4.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField5.getText()+"',"+jTextField6.getText()+",'"+jRadioButton5.getText()+"','"+jComboBox2.getSelectedItem()+"');";
                            int n=st.executeUpdate(a);
                            if(n>0)
                            {
                                JOptionPane.showMessageDialog(null,"DETAILS INSERTED");
                            }
                            else
                            {
                                JOptionPane.showMessageDialog(null,"DETAILS NOT INSERTED");
                            }
                            PASSENGER_DETAILS CONFIRM_BOOKING=new PASSENGER_DETAILS();
                            new CONFIRM_BOOKING().setVisible(true);
                         }
                         else if(jRadioButton6.isSelected())
                         {
                            String a="INSERT INTO PASSENGER_DETAILS VALUES('"+jTextField1.getText()+"',"+jTextField2.getText()+",'"+jRadioButton2.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField3.getText()+"',"+jTextField4.getText()+",'"+jRadioButton4.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField5.getText()+"',"+jTextField6.getText()+",'"+jRadioButton6.getText()+"','"+jComboBox2.getSelectedItem()+"');";
                            int n=st.executeUpdate(a);
                            if(n>0)
                            {
                                JOptionPane.showMessageDialog(null,"DETAILS INSERTED");
                            }
                            else
                            {
                                JOptionPane.showMessageDialog(null,"DETAILS NOT INSERTED");
                            }
                            PASSENGER_DETAILS CONFIRM_BOOKING=new PASSENGER_DETAILS();
                            new CONFIRM_BOOKING().setVisible(true);
                         }
                      }
                 }
            }






            else if(jComboBox2.getSelectedIndex() == 3)
            {
                    if(jComboBox1.getSelectedIndex()==0 && jRadioButton1.isSelected())
                {
                    String a="INSERT INTO PASSENGER_DETAILS VALUES('"+jTextField1.getText()+"',"+jTextField2.getText()+",'"+jRadioButton1.getText()+"','"+jComboBox2.getSelectedItem()+"');";
                    int n=st.executeUpdate(a);
                    if(n>0)
                    {
                        JOptionPane.showMessageDialog(null,"DETAILS INSERTED");
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null,"DETAILS NOT INSERTED");
                    }
                    PASSENGER_DETAILS CONFIRM_BOOKING=new PASSENGER_DETAILS();
                    new CONFIRM_BOOKING().setVisible(true);
                }
                else if(jComboBox1.getSelectedIndex() == 0 && jRadioButton2.isSelected())
                {
                    String a="INSERT INTO PASSENGER_DETAILS VALUES('"+jTextField1.getText()+"',"+jTextField2.getText()+",'"+jRadioButton2.getText()+"','"+jComboBox2.getSelectedItem()+"');";
                    int n=st.executeUpdate(a);
                    if(n>0)
                    {
                        JOptionPane.showMessageDialog(null,"DETAILS INSERTED");
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null,"DETAILS NOT INSERTED");
                    }
                    PASSENGER_DETAILS CONFIRM_BOOKING=new PASSENGER_DETAILS();
                    new CONFIRM_BOOKING().setVisible(true);
                }


                else if(jComboBox1.getSelectedIndex() == 1 && jRadioButton1.isSelected())
                {
                    if(jRadioButton3.isSelected())
                    {
                    String a="INSERT INTO PASSENGER_DETAILS VALUES('"+jTextField1.getText()+"',"+jTextField2.getText()+",'"+jRadioButton1.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField3.getText()+"',"+jTextField4.getText()+",'"+jRadioButton3.getText()+"','"+jComboBox2.getSelectedItem()+"');";
                    int n=st.executeUpdate(a);
                    if(n>0)
                    {
                        JOptionPane.showMessageDialog(null,"DETAILS INSERTED");
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null,"DETAILS NOT INSERTED");
                    }
                    PASSENGER_DETAILS CONFIRM_BOOKING=new PASSENGER_DETAILS();
                    new CONFIRM_BOOKING().setVisible(true);
                    }
                    else if(jRadioButton4.isSelected())
                    {
                        String a="INSERT INTO PASSENGER_DETAILS VALUES('"+jTextField1.getText()+"',"+jTextField2.getText()+",'"+jRadioButton1.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField3.getText()+"',"+jTextField4.getText()+",'"+jRadioButton4.getText()+"','"+jComboBox2.getSelectedItem()+"');";
                        int n=st.executeUpdate(a);
                        if(n>0)
                        {
                            JOptionPane.showMessageDialog(null,"DETAILS INSERTED");
                        }
                        else
                        {
                         JOptionPane.showMessageDialog(null,"DETAILS NOT INSERTED");
                        }
                    PASSENGER_DETAILS CONFIRM_BOOKING=new PASSENGER_DETAILS();
                    new CONFIRM_BOOKING().setVisible(true);
                    }
                }
                else if(jComboBox1.getSelectedIndex() == 1 && jRadioButton2.isSelected())
                {
                    if(jRadioButton3.isSelected())
                    {
                    String a="INSERT INTO PASSENGER_DETAILS VALUES('"+jTextField1.getText()+"',"+jTextField2.getText()+",'"+jRadioButton2.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField3.getText()+"',"+jTextField4.getText()+",'"+jRadioButton3.getText()+"','"+jComboBox2.getSelectedItem()+"');";
                    int n=st.executeUpdate(a);
                    if(n>0)
                    {
                        JOptionPane.showMessageDialog(null,"DETAILS INSERTED");
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null,"DETAILS NOT INSERTED");
                    }
                    PASSENGER_DETAILS CONFIRM_BOOKING=new PASSENGER_DETAILS();
                    new CONFIRM_BOOKING().setVisible(true);
                    }
                    else if(jRadioButton4.isSelected())
                    {
                        String a="INSERT INTO PASSENGER_DETAILS VALUES('"+jTextField1.getText()+"',"+jTextField2.getText()+",'"+jRadioButton2.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField3.getText()+"',"+jTextField4.getText()+",'"+jRadioButton4.getText()+"','"+jComboBox2.getSelectedItem()+"');";
                        int n=st.executeUpdate(a);
                        if(n>0)
                        {
                            JOptionPane.showMessageDialog(null,"DETAILS INSERTED");
                        }
                        else
                        {
                         JOptionPane.showMessageDialog(null,"DETAILS NOT INSERTED");
                        }
                    PASSENGER_DETAILS CONFIRM_BOOKING=new PASSENGER_DETAILS();
                    new CONFIRM_BOOKING().setVisible(true);
                    }
                }


                else if(jComboBox1.getSelectedIndex()==2 && jRadioButton1.isSelected())
                {
                    if(jRadioButton3.isSelected())
                    {
                        if(jRadioButton5.isSelected())
                        {
                            String a="INSERT INTO PASSENGER_DETAILS VALUES('"+jTextField1.getText()+"',"+jTextField2.getText()+",'"+jRadioButton1.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField3.getText()+"',"+jTextField4.getText()+",'"+jRadioButton3.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField5.getText()+"',"+jTextField6.getText()+",'"+jRadioButton5.getText()+"','"+jComboBox2.getSelectedItem()+"');";
                            int n=st.executeUpdate(a);
                            if(n>0)
                            {
                                JOptionPane.showMessageDialog(null,"DETAILS INSERTED");
                            }
                            else
                            {
                                JOptionPane.showMessageDialog(null,"DETAILS NOT INSERTED");
                            }
                            PASSENGER_DETAILS CONFIRM_BOOKING=new PASSENGER_DETAILS();
                            new CONFIRM_BOOKING().setVisible(true);
                        }
                        else if(jRadioButton6.isSelected())
                        {
                            String a="INSERT INTO PASSENGER_DETAILS VALUES('"+jTextField1.getText()+"',"+jTextField2.getText()+",'"+jRadioButton1.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField3.getText()+"',"+jTextField4.getText()+",'"+jRadioButton3.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField5.getText()+"',"+jTextField6.getText()+",'"+jRadioButton6.getText()+"','"+jComboBox2.getSelectedItem()+"');";
                            int n=st.executeUpdate(a);
                            if(n>0)
                            {
                                JOptionPane.showMessageDialog(null,"DETAILS INSERTED");
                            }
                            else
                            {
                                JOptionPane.showMessageDialog(null,"DETAILS NOT INSERTED");
                            }
                            PASSENGER_DETAILS CONFIRM_BOOKING=new PASSENGER_DETAILS();
                            new CONFIRM_BOOKING().setVisible(true);
                        }
                    }
                    else if(jRadioButton4.isSelected())
                    {
                        if(jRadioButton5.isSelected())
                        {
                            String a="INSERT INTO PASSENGER_DETAILS VALUES('"+jTextField1.getText()+"',"+jTextField2.getText()+",'"+jRadioButton1.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField3.getText()+"',"+jTextField4.getText()+",'"+jRadioButton4.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField5.getText()+"',"+jTextField6.getText()+",'"+jRadioButton5.getText()+"','"+jComboBox2.getSelectedItem()+"');";
                            int n=st.executeUpdate(a);
                            if(n>0)
                            {
                                JOptionPane.showMessageDialog(null,"DETAILS INSERTED");
                            }
                            else
                            {
                                JOptionPane.showMessageDialog(null,"DETAILS NOT INSERTED");
                            }
                            PASSENGER_DETAILS CONFIRM_BOOKING=new PASSENGER_DETAILS();
                            new CONFIRM_BOOKING().setVisible(true);
                        }
                        else if(jRadioButton6.isSelected())
                        {
                            String a="INSERT INTO PASSENGER_DETAILS VALUES('"+jTextField1.getText()+"',"+jTextField2.getText()+",'"+jRadioButton1.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField3.getText()+"',"+jTextField4.getText()+",'"+jRadioButton4.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField5.getText()+"',"+jTextField6.getText()+",'"+jRadioButton6.getText()+"','"+jComboBox2.getSelectedItem()+"');";
                            int n=st.executeUpdate(a);
                            if(n>0)
                            {
                                JOptionPane.showMessageDialog(null,"DETAILS INSERTED");
                            }
                            else
                            {
                                JOptionPane.showMessageDialog(null,"DETAILS NOT INSERTED");
                            }
                            PASSENGER_DETAILS CONFIRM_BOOKING=new PASSENGER_DETAILS();
                            new CONFIRM_BOOKING().setVisible(true);
                        }
                    }
                }
                else if(jComboBox1.getSelectedIndex()==2 && jRadioButton2.isSelected())
                {
                    if(jRadioButton3.isSelected())
                    {
                        if(jRadioButton5.isSelected())
                        {
                            String a="INSERT INTO PASSENGER_DETAILS VALUES('"+jTextField1.getText()+"',"+jTextField2.getText()+",'"+jRadioButton2.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField3.getText()+"',"+jTextField4.getText()+",'"+jRadioButton3.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField5.getText()+"',"+jTextField6.getText()+",'"+jRadioButton5.getText()+"','"+jComboBox2.getSelectedItem()+"');";
                            int n=st.executeUpdate(a);
                            if(n>0)
                            {
                                JOptionPane.showMessageDialog(null,"DETAILS INSERTED");
                            }
                            else
                            {
                                JOptionPane.showMessageDialog(null,"DETAILS NOT INSERTED");
                            }
                            PASSENGER_DETAILS CONFIRM_BOOKING=new PASSENGER_DETAILS();
                            new CONFIRM_BOOKING().setVisible(true);
                        }
                        else if(jRadioButton6.isSelected())
                        {
                            String a="INSERT INTO PASSENGER_DETAILS VALUES('"+jTextField1.getText()+"',"+jTextField2.getText()+",'"+jRadioButton2.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField3.getText()+"',"+jTextField4.getText()+",'"+jRadioButton3.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField5.getText()+"',"+jTextField6.getText()+",'"+jRadioButton6.getText()+"','"+jComboBox2.getSelectedItem()+"');";
                            int n=st.executeUpdate(a);
                            if(n>0)
                            {
                                JOptionPane.showMessageDialog(null,"DETAILS INSERTED");
                            }
                            else
                            {
                                JOptionPane.showMessageDialog(null,"DETAILS NOT INSERTED");
                            }
                            PASSENGER_DETAILS CONFIRM_BOOKING=new PASSENGER_DETAILS();
                            new CONFIRM_BOOKING().setVisible(true);
                        }
                      }
                      else if(jRadioButton4.isSelected())
                      {
                        if(jRadioButton5.isSelected())
                        {
                            String a="INSERT INTO PASSENGER_DETAILS VALUES('"+jTextField1.getText()+"',"+jTextField2.getText()+",'"+jRadioButton2.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField3.getText()+"',"+jTextField4.getText()+",'"+jRadioButton4.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField5.getText()+"',"+jTextField6.getText()+",'"+jRadioButton5.getText()+"','"+jComboBox2.getSelectedItem()+"');";
                            int n=st.executeUpdate(a);
                            if(n>0)
                            {
                                JOptionPane.showMessageDialog(null,"DETAILS INSERTED");
                            }
                            else
                            {
                                JOptionPane.showMessageDialog(null,"DETAILS NOT INSERTED");
                            }
                            PASSENGER_DETAILS CONFIRM_BOOKING=new PASSENGER_DETAILS();
                            new CONFIRM_BOOKING().setVisible(true);
                         }
                         else if(jRadioButton6.isSelected())
                         {
                            String a="INSERT INTO PASSENGER_DETAILS VALUES('"+jTextField1.getText()+"',"+jTextField2.getText()+",'"+jRadioButton2.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField3.getText()+"',"+jTextField4.getText()+",'"+jRadioButton4.getText()+"','"+jComboBox2.getSelectedItem()+"'),('"+jTextField5.getText()+"',"+jTextField6.getText()+",'"+jRadioButton6.getText()+"','"+jComboBox2.getSelectedItem()+"');";
                            int n=st.executeUpdate(a);
                            if(n>0)
                            {
                                JOptionPane.showMessageDialog(null,"DETAILS INSERTED");
                            }
                            else
                            {
                                JOptionPane.showMessageDialog(null,"DETAILS NOT INSERTED");
                            }
                            PASSENGER_DETAILS CONFIRM_BOOKING=new PASSENGER_DETAILS();
                            new CONFIRM_BOOKING().setVisible(true);
                         }
                      }
                 }
            }
        
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
            System.exit(0);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        PASSENGER_DETAILS CONTACT_DETAILS=new PASSENGER_DETAILS();
        new CONTACT_DETAILS().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PASSENGER_DETAILS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables

}
