/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UPDATE_TRAIN.java
 *
 * Created on Oct 31, 2019, 12:46:27 AM
 */

/**
 *
 * @author Admin
 */
import java.sql.*;
import javax.swing.*;
public class UPDATE_TRAIN extends javax.swing.JFrame {
     Connection con=null;
    Statement st=null;
    ResultSet rs=null;

    /** Creates new form UPDATE_TRAIN */
    public UPDATE_TRAIN() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("UPDATE TRAIN");

        jPanel1.setForeground(new java.awt.Color(240, 240, 240));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("UPDATE TRAIN DETAILS");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(310, 45, 216, 22);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("TRAIN NAME");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(65, 127, 86, 17);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ARRIVALTIME");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(241, 127, 93, 17);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DEPARTING TIME");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(450, 130, 118, 17);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DEPARTING DATE");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(674, 127, 120, 17);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(26, 192, 146, 31);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(220, 192, 149, 31);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(435, 190, 164, 34);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(652, 189, 163, 36);

        jButton1.setFont(new java.awt.Font("Arial", 1, 14));
        jButton1.setText("UPDATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(197, 308, 89, 27);

        jButton2.setFont(new java.awt.Font("Arial", 1, 14));
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(513, 308, 100, 27);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/update_image.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(0, 0, 880, 440);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 881, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try
        {
            con=DriverManager.getConnection("jdbc:mysql://localhost/RAILWAY","root","root");
            st=con.createStatement();
            String tn=jTextField1.getText();
            String at=jTextField2.getText();
            String dt=jTextField3.getText();
            String dd=jTextField4.getText();
            String sql1="UPDATE TRAIN SET ARRIVAL_TIME='"+at+"', DEPARTING_TIME='"+dt+"', DEPARTING_DATE='"+dd+"' WHERE TRAIN_NAME='"+tn+"';";
            int l=st.executeUpdate(sql1);
            if(l>0)
            {
                JOptionPane.showMessageDialog(null,"DETAILS UPDATED");
            }
            st.close();
            con.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
            System.exit(0);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        ADD_TRAIN ADMIN=new ADD_TRAIN();
        new ADMIN().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try
                {
                    Class.forName("java.sql.DriverManager");
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null, e.getMessage());
                    System.exit(0);
                }
                new UPDATE_TRAIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables

}
